apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikiviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikiviews
  template:
    metadata:
      labels:
        app: wikiviews
    spec:
      containers:
      - name: wikiviews
        image: moncompte/wikiviews:latest
        ports:
        - containerPort: 8000
        # Tu peux ajouter des resources, env, etc.
---
apiVersion: v1
kind: Service
metadata:
  name: wikiviews-service
spec:
  type: NodePort
  selector:
    app: wikiviews
  ports:
    - port: 80        # Port interne du Service
      targetPort: 8000 # Port du conteneur
      nodePort: 30080  # Le port exposé sur le Node

